apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    # Vault auth for reading secrets.
    vault.hashicorp.com/agent-inject: "false"
