// Copyright 2025 MCTL Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package evidence

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// Golden-vector conformance (tasks.md T1, blocking): CanonicalContentJSON,
// ContentHash and EvidenceIDFor must reproduce, byte for byte, the
// content_hash and evidence_id Tier A's seal() derives.
//
// Every vector was produced by Tier A itself, not by this package:
// investigator-, implementer- and shepherd-evidence.json are byte-for-byte
// copies of mctlhq/mctl-agents@9fe775f:tests/fixtures/evidence/ (ADR 018
// Amendment 1, PR #540): we_-only, ex_-only and both identities.
// non-ascii-evidence.json (Cyrillic, CJK, a non-BMP emoji) and
// html-chars-evidence.json (<, >, &, quote) were sealed by
// orchestrator/execution_evidence.seal() at that same commit and pass its
// from_dict/recompute_content_hash. goldenHashes pins each expected hash, so
// a fixture regenerated by anything else fails here instead of passing
// against itself.
var goldenHashes = map[string]string{
	"investigator-evidence.json": "sha256:624602c79c9fe0cf74954f51d838c01c72434071279c52b767dcc43d228dd656",
	"implementer-evidence.json":  "sha256:28b12deda5b9a546aa12f004fca51071e956ad4c1ffcad3308e46b0fa2daa564",
	"shepherd-evidence.json":     "sha256:13362a728651f5ffaa2b899b238545c6aaa77c7dac903cc43c39634700603dd7",
	"non-ascii-evidence.json":    "sha256:e47cf92c53c7b45a5c4001d6c1ed71e594cfe2929272ec817da29d256e8e0e04",
	"html-chars-evidence.json":   "sha256:6d30924febe84beeb1af004991302a24c843a710841ddbf028412cd5ff7c7430",
}

func TestGoldenVectorConformance(t *testing.T) {
	entries, err := os.ReadDir("testdata")
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	found := 0
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		found++
		t.Run(entry.Name(), func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join("testdata", entry.Name()))
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			var wire struct {
				EvidenceID  string `json:"evidence_id"`
				ContentHash string `json:"content_hash"`
			}
			if err := json.Unmarshal(raw, &wire); err != nil {
				t.Fatalf("unmarshal fixture: %v", err)
			}
			want, pinned := goldenHashes[entry.Name()]
			if !pinned {
				t.Fatalf("fixture %s has no pinned Tier A hash in goldenHashes", entry.Name())
			}
			if wire.ContentHash != want {
				t.Fatalf("fixture content_hash = %s, want the Tier A value %s", wire.ContentHash, want)
			}

			p, gotHash, gotID, err := Validate(IngestInput{EnvelopeBytes: raw})
			if err != nil {
				t.Fatalf("Validate() = %v, want success", err)
			}
			if gotHash != wire.ContentHash {
				t.Errorf("content_hash = %s, want %s", gotHash, wire.ContentHash)
			}
			if gotID != wire.EvidenceID {
				t.Errorf("evidence_id = %s, want %s", gotID, wire.EvidenceID)
			}

			// Recompute independently through the two lower-level
			// functions too, so a bug in Validate() cannot hide a bug in
			// CanonicalContentJSON/ContentHash/EvidenceIDFor.
			canonical, err := CanonicalContentJSON(p)
			if err != nil {
				t.Fatalf("CanonicalContentJSON: %v", err)
			}
			if h := ContentHash(canonical); h != wire.ContentHash {
				t.Errorf("ContentHash(CanonicalContentJSON(p)) = %s, want %s", h, wire.ContentHash)
			}
			if id := EvidenceIDFor(wire.ContentHash); id != wire.EvidenceID {
				t.Errorf("EvidenceIDFor(%s) = %s, want %s", wire.ContentHash, id, wire.EvidenceID)
			}
		})
	}
	if found == 0 {
		t.Fatal("no golden vectors found in testdata/")
	}
	if found < 5 {
		t.Fatalf("expected at least 5 golden vectors (investigator/implementer/shepherd/non-ascii/html), found %d", found)
	}
}

// TestBlankRuntimeExecutionIDHashesAsAbsent proves the Amendment 1 leaf
// rule: a received "runtime_execution_id": "" hashes exactly as if the key
// were never supplied at all (requirements.md, tasks.md task 2).
func TestBlankRuntimeExecutionIDHashesAsAbsent(t *testing.T) {
	withBlank := envelopeJSON(t, map[string]any{
		"execution_id":         "we_01hzzzzzzzzzzzzzzzzzzzzzzz",
		"work_item_id":         "wi_abc123",
		"trace_id":             "tttttttttttttttttttttttttttttttt",
		"runtime_execution_id": "",
	})
	without := envelopeJSON(t, map[string]any{
		"execution_id": "we_01hzzzzzzzzzzzzzzzzzzzzzzz",
		"work_item_id": "wi_abc123",
		"trace_id":     "tttttttttttttttttttttttttttttttt",
	})
	pBlank, err := parseEnvelope(withBlank)
	if err != nil {
		t.Fatalf("parse (blank): %v", err)
	}
	pWithout, err := parseEnvelope(without)
	if err != nil {
		t.Fatalf("parse (without): %v", err)
	}
	cBlank, err := CanonicalContentJSON(pBlank)
	if err != nil {
		t.Fatalf("canonical (blank): %v", err)
	}
	cWithout, err := CanonicalContentJSON(pWithout)
	if err != nil {
		t.Fatalf("canonical (without): %v", err)
	}
	if !bytes.Equal(cBlank, cWithout) {
		t.Errorf("canonical bytes differ:\n  blank:   %s\n  without: %s", cBlank, cWithout)
	}
}

// envelopeJSON builds a minimal, otherwise-valid envelope with the given
// execution block, self-sealed (evidence_id/content_hash filled in by
// hashing it once), so tests can focus on one field at a time.
func envelopeJSON(t *testing.T, execution map[string]any) []byte {
	t.Helper()
	base := map[string]any{
		"api_version":  APIVersionV1Alpha1,
		"kind":         KindV1Alpha1,
		"evidence_id":  "",
		"content_hash": "sha256:0000000000000000000000000000000000000000000000000000000000000000",
		"created_at":   "2026-01-15T12:00:00Z",
		"execution":    execution,
		"outcome":      map[string]any{"code": "succeeded", "reason_code": "test"},
	}
	raw, err := json.Marshal(base)
	if err != nil {
		t.Fatalf("marshal base envelope: %v", err)
	}
	p, err := parseEnvelope(raw)
	if err != nil {
		t.Fatalf("parse base envelope: %v", err)
	}
	canonical, err := CanonicalContentJSON(p)
	if err != nil {
		t.Fatalf("canonical base envelope: %v", err)
	}
	hash := ContentHash(canonical)
	base["content_hash"] = hash
	base["evidence_id"] = EvidenceIDFor(hash)
	sealed, err := json.Marshal(base)
	if err != nil {
		t.Fatalf("marshal sealed envelope: %v", err)
	}
	return sealed
}

func TestValidateRejectsUnsupportedAPIVersion(t *testing.T) {
	raw := envelopeJSON(t, map[string]any{"execution_id": "we_x"})
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	bumped, _ := json.Marshal("evidence.mctl.ai/v2")
	m["api_version"] = bumped
	raw2, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	_, _, _, err = Validate(IngestInput{EnvelopeBytes: raw2})
	if !errors.Is(err, ErrUnsupportedAPIVersion) {
		t.Fatalf("Validate() error = %v, want ErrUnsupportedAPIVersion", err)
	}
}

func TestValidateRejectsHashMismatch(t *testing.T) {
	raw := envelopeJSON(t, map[string]any{"execution_id": "we_x"})
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	tampered, _ := json.Marshal("sha256:" + "ab" + "0000000000000000000000000000000000000000000000000000000000000"[2:])
	m["content_hash"] = tampered
	raw2, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	_, _, _, err = Validate(IngestInput{EnvelopeBytes: raw2})
	if !errors.Is(err, ErrEvidenceHashMismatch) {
		t.Fatalf("Validate() error = %v, want ErrEvidenceHashMismatch", err)
	}
}

func TestValidateRejectsOversizeEnvelope(t *testing.T) {
	big := make([]byte, MaxEvidenceBytes+1)
	_, _, _, err := Validate(IngestInput{EnvelopeBytes: big})
	if !errors.Is(err, ErrEvidenceTooLarge) {
		t.Fatalf("Validate() error = %v, want ErrEvidenceTooLarge", err)
	}
}

func TestValidateRejectsUnknownKeys(t *testing.T) {
	raw := envelopeJSON(t, map[string]any{"execution_id": "we_x"})
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	m["bogus_field"] = json.RawMessage(`"nope"`)
	raw2, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	_, _, _, err = Validate(IngestInput{EnvelopeBytes: raw2})
	if !errors.Is(err, ErrEvidenceInvalid) {
		t.Fatalf("Validate() error = %v, want ErrEvidenceInvalid", err)
	}
}

func TestValidateRejectsDuplicateKeys(t *testing.T) {
	raw := []byte(`{"api_version":"evidence.mctl.ai/v1alpha1","api_version":"evidence.mctl.ai/v1alpha1","kind":"ExecutionEvidence","evidence_id":"ev-0000000000000000","content_hash":"sha256:0000000000000000000000000000000000000000000000000000000000000000","created_at":"2026-01-15T12:00:00Z","execution":{"execution_id":"we_x","work_item_id":"","trace_id":""},"outcome":{"code":"","reason_code":""}}`)
	_, _, _, err := Validate(IngestInput{EnvelopeBytes: raw})
	if !errors.Is(err, ErrEvidenceInvalid) {
		t.Fatalf("Validate() error = %v, want ErrEvidenceInvalid", err)
	}
}

func TestExecutionJoinValidation(t *testing.T) {
	cases := []struct {
		name    string
		join    executionJoin
		wantErr bool
	}{
		{"work only", executionJoin{ExecutionID: "we_abc"}, false},
		{"runtime only", executionJoin{RuntimeExecutionID: "ex-0123456789abcdef"}, false},
		{"both", executionJoin{ExecutionID: "we_abc", RuntimeExecutionID: "ex-0123456789abcdef"}, false},
		{"both blank", executionJoin{}, true},
		{"ex- in execution_id", executionJoin{ExecutionID: "ex-0123456789abcdef"}, true},
		{"we_ in runtime_execution_id", executionJoin{RuntimeExecutionID: "we_abc"}, true},
		{"malformed runtime id (short)", executionJoin{RuntimeExecutionID: "ex-abc"}, true},
		{"malformed runtime id (uppercase)", executionJoin{RuntimeExecutionID: "ex-0123456789ABCDEF"}, true},
		{"malformed work id (no prefix)", executionJoin{ExecutionID: "abc"}, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.join.validate()
			if tc.wantErr && err == nil {
				t.Fatal("validate() = nil, want error")
			}
			if !tc.wantErr && err != nil {
				t.Fatalf("validate() = %v, want nil", err)
			}
			if tc.wantErr && !errors.Is(err, ErrInvalidExecutionRef) {
				t.Fatalf("validate() = %v, want ErrInvalidExecutionRef", err)
			}
		})
	}
}

func TestPrimaryExecutionRef(t *testing.T) {
	cases := []struct {
		name     string
		e        *Evidence
		wantKind string
		wantID   string
	}{
		{"work wins when both", &Evidence{ExecutionID: "we_a", RuntimeExecutionID: "ex-0123456789abcdef"}, "work", "we_a"},
		{"runtime only", &Evidence{RuntimeExecutionID: "ex-0123456789abcdef"}, "runtime", "ex-0123456789abcdef"},
		{"neither", &Evidence{}, "", ""},
		{"nil", nil, "", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			kind, id := tc.e.PrimaryExecutionRef()
			if kind != tc.wantKind || id != tc.wantID {
				t.Errorf("PrimaryExecutionRef() = (%q, %q), want (%q, %q)", kind, id, tc.wantKind, tc.wantID)
			}
		})
	}
}

func TestValidateRejectsMalformedCreatedAt(t *testing.T) {
	for _, bad := range []string{"", "2026-01-15", "2026-01-15T12:00:00+02:00", "2026-01-15 12:00:00Z", "2026-01-15T12:00:00.1234567Z"} {
		raw := envelopeJSON(t, map[string]any{"execution_id": "we_x"})
		var m map[string]any
		if err := json.Unmarshal(raw, &m); err != nil {
			t.Fatal(err)
		}
		m["created_at"] = bad
		raw2, err := json.Marshal(m)
		if err != nil {
			t.Fatal(err)
		}
		if _, _, _, err := Validate(IngestInput{EnvelopeBytes: raw2}); !errors.Is(err, ErrEvidenceInvalid) {
			t.Errorf("created_at %q: Validate() = %v, want ErrEvidenceInvalid", bad, err)
		}
	}
}

// A present object block enters the hashed payload even when it is {}:
// Tier A tests object blocks by presence (`is not None`), not truthiness,
// unlike list blocks. Pins the rule documented on isEmptyBlock.
func TestEmptyObjectBlockIsHashedNotOmitted(t *testing.T) {
	raw := envelopeJSON(t, map[string]any{"execution_id": "we_x"})
	var m map[string]any
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	withoutBlock, err := parseEnvelope(raw)
	if err != nil {
		t.Fatal(err)
	}
	m["usage"] = map[string]any{}
	withEmpty, err := json.Marshal(m)
	if err != nil {
		t.Fatal(err)
	}
	p, err := parseEnvelope(withEmpty)
	if err != nil {
		t.Fatal(err)
	}
	a, _ := CanonicalContentJSON(withoutBlock)
	b, _ := CanonicalContentJSON(p)
	if bytes.Equal(a, b) {
		t.Fatal("an empty usage object hashed as if absent; Tier A hashes a present object block")
	}
	// Empty lists, by contrast, are omitted.
	m["usage"] = nil
	m["policy_decisions"] = []any{}
	withEmptyList, _ := json.Marshal(m)
	pl, err := parseEnvelope(withEmptyList)
	if err != nil {
		t.Fatal(err)
	}
	c, _ := CanonicalContentJSON(pl)
	if !bytes.Equal(a, c) {
		t.Errorf("an empty policy_decisions list changed the canonical bytes; Tier A omits empty list blocks")
	}
}
